// ======================= Example Prompts =======================

const examplePrompts = [
  "Imagine a futuristic train zooming across a floating rail",
  "A breathtaking view of a steampunk robot with a garden inside its chest",
  "Imagine a ship sailing through clouds with moonlight sails",
  "Visualize a time-traveling explorer in ancient Egypt",
  "A dreamy vision of a crystal dragon curled around a mountain peak",
  "A magical depiction of a giant library built inside a volcano",
  "An ultra-detailed painting of a crystal dragon curled around a mountain peak",
  "A magical depiction of a futuristic train zooming across a floating rail",
  "An ultra-detailed painting of a desert with glass dunes and rainbow mirages",
  "A cinematic scene showing a cybernetic jungle where trees have metal leaves",
  "A fantasy artwork of a futuristic train zooming across a floating rail",
  "A fantasy artwork of a desert with glass dunes and rainbow mirages",
  "A breathtaking view of a portal opening between two fantasy worlds",
  "An ultra-detailed painting of a post-apocalyptic city reclaimed by nature",
  "A cinematic scene showing a dreamlike meadow with bioluminescent flowers",
  "A magical depiction of a floating castle anchored by chains to the earth",
  "Imagine a dragon flying over a neon cityscape",
  "An ultra-detailed painting of a glowing alien landscape under twin suns",
  "A futuristic concept of a post-apocalyptic city reclaimed by nature",
  "Visualize a child floating among planets and stardust",
  "An epic illustration of a ship sailing through clouds with moonlight sails",
  "Visualize a snow-covered village lit by floating lanterns",
  "An ultra-detailed painting of a flying whale with stars embedded in its skin",
  "A cinematic scene showing a child floating among planets and stardust",
  "An epic illustration of a cybernetic jungle where trees have metal leaves",
  "A dreamy vision of a dragon flying over a neon cityscape",
  "A magical depiction of a portal opening between two fantasy worlds",
  "A breathtaking view of a child floating among planets and stardust",
  "An epic illustration of a crystal dragon curled around a mountain peak",
  "A fantasy artwork of a steampunk robot with a garden inside its chest",
  "A dreamy vision of a futuristic train zooming across a floating rail",
  "A dreamy vision of a magical tavern hidden inside a mountain",
  "Visualize a desert with glass dunes and rainbow mirages",
  "An ultra-detailed painting of a cybernetic jungle where trees have metal leaves",
  "A cinematic scene showing a magical tavern hidden inside a mountain",
  "A cinematic scene showing a steampunk robot with a garden inside its chest",
  "A magical depiction of a cybernetic jungle where trees have metal leaves",
  "A fantasy artwork of a mystical waterfall flowing in reverse into the sky",
  "A dreamy vision of a child floating among planets and stardust",
  "A dreamy vision of a mystical waterfall flowing in reverse into the sky",
  "A magical depiction of a child floating among planets and stardust",
  "A dreamy vision of a post-apocalyptic city reclaimed by nature",
  "A futuristic concept of a cybernetic jungle where trees have metal leaves",
  "Imagine a magical tavern hidden inside a mountain",
  "Visualize a haunted victorian mansion covered in fog",
  "A dreamy vision of a portal opening between two fantasy worlds",
  "A fantasy artwork of a floating castle anchored by chains to the earth",
  "Visualize a futuristic train zooming across a floating rail",
  "A magical depiction of a ship sailing through clouds with moonlight sails",
  "Imagine a cybernetic jungle where trees have metal leaves",
  "A breathtaking view of a dragon flying over a neon cityscape",
  "A breathtaking view of a magical tavern hidden inside a mountain",
  "Imagine a crystal dragon curled around a mountain peak",
  "A futuristic concept of a mystical waterfall flowing in reverse into the sky",
  "A dreamy vision of a snow-covered village lit by floating lanterns",
  "A futuristic concept of a giant library built inside a volcano",
  "A fantasy artwork of a giant library built inside a volcano",
  "An epic illustration of a snow-covered village lit by floating lanterns",
  "A breathtaking view of a time-traveling explorer in ancient Egypt",
  "A cinematic scene showing a snow-covered village lit by floating lanterns",
  "An ultra-detailed painting of a floating castle anchored by chains to the earth",
  "Imagine a glowing alien landscape under twin suns",
  "A magical depiction of a steampunk robot with a garden inside its chest",
  "A magical depiction of a desert with glass dunes and rainbow mirages",
  "A futuristic concept of a snow-covered village lit by floating lanterns",
  "An epic illustration of a dreamlike meadow with bioluminescent flowers",
  "A magical depiction of a magical tavern hidden inside a mountain",
  "An epic illustration of a desert with glass dunes and rainbow mirages",
  "A fantasy artwork of a dreamlike meadow with bioluminescent flowers",
  "A breathtaking view of a post-apocalyptic city reclaimed by nature",
  "A dreamy vision of a steampunk robot with a garden inside its chest",
  "A fantasy artwork of a time-traveling explorer in ancient Egypt",
  "Visualize a steampunk robot with a garden inside its chest",
  "A magical depiction of a snow-covered village lit by floating lanterns",
  "A dreamy vision of a glowing alien landscape under twin suns",
  "An ultra-detailed painting of a dreamlike meadow with bioluminescent flowers",
  "A breathtaking view of a flying whale with stars embedded in its skin",
  "A cinematic scene showing a crystal dragon curled around a mountain peak",
  "A dreamy vision of a ship sailing through clouds with moonlight sails",
  "A futuristic concept of a steampunk robot with a garden inside its chest",
  "A cinematic scene showing a portal opening between two fantasy worlds",
  "A dreamy vision of a dreamlike meadow with bioluminescent flowers",
  "A fantasy artwork of a portal opening between two fantasy worlds",
  "A futuristic concept of a crystal dragon curled around a mountain peak",
  "A futuristic concept of a haunted victorian mansion covered in fog",
  "A breathtaking view of a mystical waterfall flowing in reverse into the sky",
  "A dreamy vision of a time-traveling explorer in ancient Egypt",
  "A breathtaking view of a glowing alien landscape under twin suns",
  "Visualize a cybernetic jungle where trees have metal leaves",
  "A futuristic concept of a floating castle anchored by chains to the earth",
  "A cinematic scene showing a time-traveling explorer in ancient Egypt",
  "A cinematic scene showing a desert with glass dunes and rainbow mirages",
  "A futuristic concept of a desert with glass dunes and rainbow mirages",
  "A magical depiction of a glowing alien landscape under twin suns",
  "Imagine a haunted victorian mansion covered in fog",
  "A futuristic concept of a child floating among planets and stardust",
  "Visualize a flying whale with stars embedded in its skin",
  "Visualize a magical tavern hidden inside a mountain",
  "Visualize a mystical waterfall flowing in reverse into the sky",
  "A dreamy vision of a desert with glass dunes and rainbow mirages",
  "An ultra-detailed painting of a steampunk robot with a garden inside its chest",
  "Imagine a child floating among planets and stardust",
  "Imagine a giant library built inside a volcano",
  "Visualize a crystal dragon curled around a mountain peak",
  "An ultra-detailed painting of a haunted victorian mansion covered in fog",
  "A magical depiction of a time-traveling explorer in ancient Egypt",
  "An ultra-detailed painting of a child floating among planets and stardust",
  "A breathtaking view of a snow-covered village lit by floating lanterns",
  "A cinematic scene showing a glowing alien landscape under twin suns",
  "A breathtaking view of a cybernetic jungle where trees have metal leaves",
  "An epic illustration of a time-traveling explorer in ancient Egypt",
  "A breathtaking view of a floating castle anchored by chains to the earth",
  "Visualize a floating castle anchored by chains to the earth",
  "A breathtaking view of a ship sailing through clouds with moonlight sails",
  "An ultra-detailed painting of a giant library built inside a volcano",
  "A magical depiction of a post-apocalyptic city reclaimed by nature",
  "A magical depiction of a mystical waterfall flowing in reverse into the sky",
  "A fantasy artwork of a crystal dragon curled around a mountain peak",
  "Visualize a post-apocalyptic city reclaimed by nature",
  "A magical depiction of a dragon flying over a neon cityscape",
  "An epic illustration of a dragon flying over a neon cityscape",
  "Imagine a dreamlike meadow with bioluminescent flowers",
  "An epic illustration of a steampunk robot with a garden inside its chest",
  "A breathtaking view of a haunted victorian mansion covered in fog",
  "An ultra-detailed painting of a mystical waterfall flowing in reverse into the sky",
  "Imagine a time-traveling explorer in ancient Egypt",
  "Imagine a post-apocalyptic city reclaimed by nature",
  "A dreamy vision of a giant library built inside a volcano",
  "A futuristic concept of a ship sailing through clouds with moonlight sails",
  "A cinematic scene showing a flying whale with stars embedded in its skin",
  "A cinematic scene showing a haunted victorian mansion covered in fog",
  "An ultra-detailed painting of a time-traveling explorer in ancient Egypt",
  "A magical depiction of a flying whale with stars embedded in its skin",
  "A dreamy vision of a cybernetic jungle where trees have metal leaves",
  "A fantasy artwork of a flying whale with stars embedded in its skin",
  "A fantasy artwork of a cybernetic jungle where trees have metal leaves",
  "Visualize a dragon flying over a neon cityscape",
  "An epic illustration of a futuristic train zooming across a floating rail",
  "A magical depiction of a crystal dragon curled around a mountain peak",
  "Visualize a ship sailing through clouds with moonlight sails",
  "Imagine a desert with glass dunes and rainbow mirages",
  "A cinematic scene showing a mystical waterfall flowing in reverse into the sky",
  "A fantasy artwork of a child floating among planets and stardust",
  "A futuristic concept of a futuristic train zooming across a floating rail",
  "A cinematic scene showing a futuristic train zooming across a floating rail",
  "An epic illustration of a flying whale with stars embedded in its skin",
  "A fantasy artwork of a post-apocalyptic city reclaimed by nature",
  "Imagine a snow-covered village lit by floating lanterns",
  "A futuristic concept of a portal opening between two fantasy worlds",
  "A futuristic concept of a magical tavern hidden inside a mountain",
  "A futuristic concept of a glowing alien landscape under twin suns",
  "A cinematic scene showing a floating castle anchored by chains to the earth",
  "Visualize a giant library built inside a volcano",
  "An ultra-detailed painting of a futuristic train zooming across a floating rail",
  "An ultra-detailed painting of a dragon flying over a neon cityscape",
  "A futuristic concept of a time-traveling explorer in ancient Egypt",
  "An epic illustration of a floating castle anchored by chains to the earth",
  "A futuristic concept of a dreamlike meadow with bioluminescent flowers",
  "An ultra-detailed painting of a snow-covered village lit by floating lanterns",
  "A fantasy artwork of a magical tavern hidden inside a mountain",
  "A fantasy artwork of a dragon flying over a neon cityscape",
  "A cinematic scene showing a giant library built inside a volcano",
  "A dreamy vision of a floating castle anchored by chains to the earth",
  "An epic illustration of a giant library built inside a volcano",
  "A breathtaking view of a dreamlike meadow with bioluminescent flowers",
  "Imagine a flying whale with stars embedded in its skin",
  "A dreamy vision of a haunted victorian mansion covered in fog",
  "A cinematic scene showing a dragon flying over a neon cityscape",
  "A breathtaking view of a giant library built inside a volcano",
  "A dreamy vision of a flying whale with stars embedded in its skin",
  "An epic illustration of a child floating among planets and stardust",
  "Visualize a portal opening between two fantasy worlds",
  "A breathtaking view of a crystal dragon curled around a mountain peak",
  "An epic illustration of a mystical waterfall flowing in reverse into the sky",
  "An epic illustration of a post-apocalyptic city reclaimed by nature",
  "A breathtaking view of a futuristic train zooming across a floating rail",
  "A fantasy artwork of a snow-covered village lit by floating lanterns",
  "A cinematic scene showing a post-apocalyptic city reclaimed by nature",
  "A cinematic scene showing a ship sailing through clouds with moonlight sails",
  "An ultra-detailed painting of a ship sailing through clouds with moonlight sails",
  "Visualize a dreamlike meadow with bioluminescent flowers",
  "Imagine a steampunk robot with a garden inside its chest",
  "A breathtaking view of a desert with glass dunes and rainbow mirages",
  "An epic illustration of a magical tavern hidden inside a mountain",
  "An epic illustration of a glowing alien landscape under twin suns",
  "A futuristic concept of a flying whale with stars embedded in its skin",
  "An epic illustration of a haunted victorian mansion covered in fog",
  "Imagine a mystical waterfall flowing in reverse into the sky",
  "A fantasy artwork of a glowing alien landscape under twin suns",
  "A magical depiction of a dreamlike meadow with bioluminescent flowers",
  "A magical depiction of a haunted victorian mansion covered in fog",
  "An ultra-detailed painting of a portal opening between two fantasy worlds",
  "Imagine a floating castle anchored by chains to the earth",
  "A futuristic concept of a dragon flying over a neon cityscape",
  "Imagine a portal opening between two fantasy worlds",
  "A fantasy artwork of a ship sailing through clouds with moonlight sails",
  "A fantasy artwork of a haunted victorian mansion covered in fog",
  "An epic illustration of a portal opening between two fantasy worlds",
  "An ultra-detailed painting of a magical tavern hidden inside a mountain",
  "Visualize a glowing alien landscape under twin suns",
  "A magic forest with glowing plants and fairy homes among giant mushrooms",
  "An old steampunk airship floating through golden clouds at sunset",
  "A future Mars colony with glass domes and gardens against red mountains",
  "A dragon sleeping on gold coins in a crystal cave",
  "An underwater kingdom with merpeople and glowing coral buildings",
  "A floating island with waterfalls pouring into clouds below",
  "A witch's cottage in fall with magic herbs in the garden",
  "A robot painting in a sunny studio with art supplies around it",
  "A magical library with floating glowing books and spiral staircases",
  "A Japanese shrine during cherry blossom season with lanterns and misty mountains",
  "A cosmic beach with glowing sand and an aurora in the night sky",
  "A medieval marketplace with colorful tents and street performers",
  "A cyberpunk city with neon signs and flying cars at night",
  "A peaceful bamboo forest with a hidden ancient temple",
  "A giant turtle carrying a village on its back in the ocean",
];
